- PATENTS
- README.md
Added the PATENTS file and brief description of intended usage and file
placement in the README.
> Add patents file, update the readme

- grpc/channelz/channelz.proto
@ejona86 @zpencer @lyuxuan 
In a later PR, I will update the proposal directory.     This version will be the canonical proto, and I will find a way to auto import it.
> Move channelz proto to grpc-proto

- BUILD.bazel
- grpc/health/v1/health.proto
This version incorporates all differences from the 3 languages
> Add health.proto

- BUILD.bazel
- grpc/channelz/v1/channelz.proto
Discussed with @a11r and @dfawley
> add version to channelz package

- BUILD.bazel
- WORKSPACE
- grpc/channelz/v1/channelz.proto
- grpc/gcp/altscontext.proto
- grpc/gcp/handshaker.proto
- grpc/gcp/transport_security_common.proto
- grpc/health/v1/health.proto
> Normalize Copyright headers

- grpc/channelz/v1/channelz.proto
Sourced from https://github.com/grpc/proposal/blob/master/A3-channel-tracing.md#format-of-exported-data
> Complete ChannelTrace in channelz.proto

- BUILD.bazel
- grpc/lb/v1/load_balancer.proto
> Add grpclb load balancer proto

- grpc/lb/v1/load_balancer.proto
Requested [here](https://github.com/grpc/grpc/issues/8363#issuecomment-360280024).
> Update comment of LB token

- grpc/binlog/v1/binarylog.proto
- grpc/binlog/v1alpha/binarylog.proto
Add v1 binlog as defined in:
https://github.com/grpc/proposal/blob/master/A16-binary-logging.md
> Add v1 binlog, deprecated v1alpha binlog

- BUILD.bazel
> :reflection_java_proto_deprecated must be public

- grpc/service_config/service_config.proto
This is not actually used by anything externally, but we've had several people ask for us to publish this as a reference.
> Service config proto

- .travis.yml
Turn it off! Turn it off! TURN IT OFF!!
> travis.yml: Disable email notifications

- grpc/gcp/handshaker.proto
Design doc - go/seal-frame-size-negotiation-alts
> Added max_frame_size field for implementing frame size negotiation in ALTS

- BUILD.bazel
- grpc/channelz/v1/channelz.proto
- grpc/lb/v1/load_reporter.proto
- Fixed a typo in `grpc/channelz/v1/channelz.proto`
- Added `grpc/lb/v1/load_reporter.proto`
> Sync Protos from grpc/grpc

- grpc/service_config/service_config.proto
These changes are described in grpc/proposal#281.
> Add outlier_detection LB policy config

- grpc/testing/messages.proto
https://github.com/grpc/grpc/pull/29632
cc. @markdroth @dfawley
> add orca test report and request fields

- grpc/service_config/service_config.proto
> Include least_request LB config in service_config

- grpc/testing/messages.proto
discussed in https://github.com/grpc/grpc-java/pull/9260
> add orca_oob_report to message.proto stremaingoutputcallrequest

- BUILD.bazel
- grpc/testing/control.proto
The control.proto in grpc/grpc was updated by 
https://github.com/grpc/grpc/pull/29207. This pr updates
the control.proto file in this repo to be in sync with
control.proto in grpc/grpc.
> Update control.proto to be in sync with the one in grpc/grpc.

- grpc/reflection/v1alpha/reflection.proto
Blocking build of go pb files as per https://github.com/grpc/grpc-go/actions/runs/3424244241/jobs/5703697675#step:4:154
> Update spelling error in reflection v1alpha

- grpc/service_config/service_config.proto
See: https://github.com/grpc/proposal/pull/357
> Add  option to pick_first config

- grpc/service_config/service_config.proto
> service config: update xDS LB policy configs for gRFC A74

- grpc/gcp/s2a/s2a.proto
https://github.com/grpc/grpc-proto/issues/150
> Fix s2a.proto error

- grpc/lookup/v1/rls_config.proto
> RLS config: update comments on max_age and stale_age
