grpc/grpc-proto

- grpc/channelz/channelz.proto
- links to the canonical path (so it can be copied more easily)
- Adds a go_package name rather than relying on the file name
- Adds docs to most fields and messages with expectations about if they should be set.
> Add more docs to channelz proto

- BUILD.bazel
- grpc/gcp/altscontext.proto
- grpc/gcp/handshaker.proto
- grpc/gcp/transport_security_common.proto
This moves the ALTS protos to a standard, common location.  In the future, when the golden files are updated inside of google, they will propagate to here first, and then down to each of the repos.  This should make it easier to keep all of them in sync.
cc: @cesarghali @jiangtaoli2016 @dfawley
> make ALTS protos available in grpc-proto

- grpc/binlog/v1alpha/binarylog.proto
Using sockaddr_in is leaking C implementation details into the proto.
Since we really only care about address and port, let's just store
exactly that. This makes it much easier for tooling and non-C gRPC
implementations to deal with Peer.
> binarylogs: split peer address and port into separate fields

- grpc/binlog/v1alpha/binarylog.proto
Different languages may show different information to applications via
the metadata. Document this behavior and ensure that universally
required info is denormalized into the proto.
> binarylog: move required info from metadata to top level fields

- grpc/lb/v1/load_balancer.proto
I changed this in grpc repo before. I feel it's worth keeping because it does clarify the port thing.
> Update LB proto comment again

- grpc/lb/v1/load_balancer.proto
There are no Java users of this proto internally, so this won't cause problems during the sync.
grpc/grpc-java#4705
> Fix grpclb's java_package to match the proto and include version

- grpc/binlog/v1alpha/binarylog.proto
Since this is a breaking change, it will need to be coordinated with the Java sync.
grpc/grpc-java#4704
> Fix binarylog's java_package to include version

- BUILD.bazel
- grpc/testing/report_qps_scenario_service.proto
The import path should reflect what is in this repo. During import to
internal, there are rules that expect this convention.
> Fix import path

- BUILD.bazel
- grpc/reflection/v1alpha/reflection.proto
For the sake of completeness, let's add the file to this repo during
the transitional period.
> Add v1alpha reflection

- grpc/channelz/v1/channelz.proto
This requires tweaking how pagination works. Otherwise, it would not
be possible to paginate 1 result at a time. This implies that 0 MUST
NOT be a valid ID for any channelz entity.
See https://github.com/grpc/proposal/pull/114
> Add result cardinality limit to requests.

- grpc/channelz/v1/channelz.proto
If set, only return a high level summary.
I don't think the security info is relevant either for the high level view of a socket. I can revert this if we disagree.
Even though any field can be absent in proto3, it's probably still a good idea to document what 'summary' should suppress. Otherwise it's not clear if socket addresses, `last_local_stream_created_timestamp`, or `last_message_sent_timestamp` is expected to be present.
> Add 'summary' field to GetSocketRequest

- BUILD.bazel
- WORKSPACE
This makes it possible for grpc-java to properly depend on the java protos it needs to in its services/ source tree.
NOTE: This also upgrades protobuf to a newer version and fixes more recent Bazel deprecation errors.
Everything builds fine.
> adds java_proto_library rules for all public protos.

- BUILD.bazel
gRPC still makes use of it currently:
https://github.com/grpc/grpc-java/pull/5384
> deprecated reflection proto must be exposed.

- BUILD.bazel
grpc-java was ported to v1.
I could have sworn it was v1alpha, but I see references to v1 in my other PR:
https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/services/BinlogHelper.java
> Switch to binarylog_proto v1.

- BUILD.bazel
Hello again. I believe this is the final time I will be doing this.
I've verified that I can do: `bazel build grpc-java/services/...`  successfully.
FWIW, this repository should probably have some build automation which could have saved us all a bunch of time.
> Adding timestamp dep to binarylog_proto

- grpc/testing/messages.proto
These fields facilitate testing of certain client load balancing policies
> Add fill_server_id and server_id fields to SimpleRequest/Response

- grpc/testing/messages.proto
This is in order to add a couple of new tests around grpclb fallback
Test descriptions already discussed offline
> Add optional grpclb_path field to SimpleResponse

- grpc/testing/messages.proto
Fixes a lint error complaining that this enum should have a prefix or suffix to distinguish with other enums within the same namespace.
> Add a prefix to new enums in messages.proto to fix a lint error

- grpc/service_config/service_config.proto
- Deprecate balancer_name field, since we are now getting that info via
the bootstrap file.
- Add eds_service_name field, so that the CDS policy can tell the EDS
policy what name to use in the EDS query.  (For backward
compatibility, if this field is not set, it will default to the server
name from the channel's target URI.)
- Add lrs_load_reporting_server_name field to indicate whether LRS load
reporting should be enabled.
- Add CdsConfig message for cds policy.
> Update xds LB policy config proto

- grpc/lookup/v1/rls_config.proto
Clarify how an unhealthy returned target should be handled.
> Update comment for RouteLookupConfig.valid_targets

- grpc/lb/v1/load_balancer.proto
To support scenarios where we want the load balancer to explicitly tell a client to eagerly enter fallback mode.
> Add fallback_response type to load balance response message

- grpc/service_config/service_config.proto
This will be used by rls to override the name of the target to be sent
to the remote balancer.
> grpc/service_config: Add target_name field to grpclb config.

- grpc/service_config/service_config.proto
MethodConfig:
- Allow a default config where service name is not set
- Clarify validation
LoadBalancingConfig:
- Clarify validation
> service_config: update doc for MethodConfig and LoadBalancingConfig

- grpc/lookup/v1/rls_config.proto
Rather than mean "no caching", it instead means "maximum caching".
Consensus is that we don't want to allow disabling caching by setting
max_age to zero.
> Change semantics for max_age missing or zero

- grpc/lb/v1/load_balancer.proto
It was part of the initial design but then scrapped early in grpclb's
life. No client has supported it. Remove it to prevent confusion.
@vishalpowar, would you confirm my understanding is correct, that
nothing uses this? I didn't see any users internally.
CC @wicharypawel
> load_balancer: Remove never-used load_balancer_delegate

- grpc/examples/helloworld.proto
As discussed with @ejona86.
The version submitted here was copied from the `grpc-go` repo: [grpc-go/examples/helloworld/helloworld/helloworld.proto](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.proto). No changes have been made to this copy.
Eric, we had discussed possible changes such as: adding a canonical link as a comment, and possibly additional language options. Would you like those added to this PR or a followup PR?
cc @dfawley @menghanl
> Add examples/helloworld.proto

- grpc/lookup/v1/rls.proto
- grpc/lookup/v1/rls_config.proto
The RouteLookupResponse.target field was deprecated and is no longer
in use by any server or client, so remove entirely.
The RouteLookupConfig.request_processing_strategy was likewise
deprecated when ASYNC_LOOKUP_DEFAULT_TARGET_ON_MISS stopped being
supported and it became equivalent to just a presence check on
default_target, so remove it now.
> Clean up unused fields in grpc/lookup/v1 protos

- README.md
This also removes the expectation of the sanity tests, mainly because
they never were created and were canned before being created because
they were originally invisioned to be CI tests, which would fail PRs the
moment a comment was made to grpc-proto.
We are instead using scripts and other solutions to keep the chances of
manual changes low, while only using a single copy of the protos
in Google's internal build. Since repositories sync to Google-internal
frequently, manual changes that "get through the cracks" and break
functionality should still be discovered promptly.
Not all of that is in the README, though, because it proved hard to
integrate such that the prose was still short and to the point, while
also not being confusing to non-Google-devs. And I don't actually expect
many …
> README.md: Expand the expected usage description

- grpc/tls/provider/meshca/experimental/config.proto
MeshCA plugin code will reside at: `google.golang.org/grpc/credentials/tls/certprovider/meshca/`
MeshCA generated protos will reside at: `google.golang.org/grpc/credentials/tls/certprovider/meshca/internal/meshca_experimental`
> Add go_package option to meshca config proto.

- grpc/testing/messages.proto
The newly added "result" map serves the same function as the existing "rpcs succeeded/failed", but also allows for us to verify the *type* of failure; this is necessary for testing that exceeding RPC timeouts results in DEADLINE_EXCEEDED.  The structure (one map from method to a struct) should also be a bit easier to use (multiple maps from method to scalars).
> grpc/testing: add new stats for RPC results and ability to set RPC timeouts dynamically

- BUILD.bazel
- grpc/auth/v1/authz_policy.proto
Defines SDK Authorization Policy proto. This is required for gRPC OSS Authorization effort, allowing non-xDS users to provide an authorization policy.
> Add SDK Authorization Policy proto.

- grpc/testing/messages.proto
Go and C both implemented this feature using the same key as the existing stats maps in this message: the `RpcType` as a string.  This seems preferable to the full method name, for consistency.  This PR updates the docstring to match that.
> grpc/testing: update docstring of stats_per_method to reflect reality

- grpc/lookup/v1/rls.proto
This information can be used at the RLS server and joined with request
logs from the backends to help determine RLS cache hit percentage
at a per-project granularity.
> Add RouteLookupRequest::reason field to indicate MISS or STALE

- grpc/lookup/v1/rls.proto
This field echoes back the RouteLookupResponse.header_data field from
the stale cached value for REASON_STALE requests. This can be helpful,
for example, if the RLS server can prioritize serving stale requests
over new requests.
> Add RouteLookupRequest.stale_header_data

- grpc/service_config/service_config.proto
- adds missing "_experimental" prefix to priority and weighted_target policies
- sets proper JSON name for weighted_target policy
- applies changes from [gRFC A37](https://github.com/grpc/proposal/blob/master/A37-xds-aggregate-and-logical-dns-clusters.md) and [gRFC A42](https://github.com/grpc/proposal/blob/master/A42-xds-ring-hash-lb-policy.md)
Fixes #95
> service config LB policy update

- BUILD.bazel
- grpc/service_config/service_config.proto
- Add `XdsServer` message and use it in new fields in `xds_cluster_resolver_experimental` and `xds_cluster_impl_experimental` configs, as per the latest draft of grpc/proposal#268
- Deprecate `eds_experimental` policy config, as per [gRFC A37](https://github.com/grpc/proposal/blob/master/A37-xds-aggregate-and-logical-dns-clusters.md)
- Add missing config for `xds_cluster_manager_experimental` policy, as per [gRFC A31](https://github.com/grpc/proposal/blob/master/A31-xds-timeout-support-and-config-selector.md)
> more LB policy config updates

- BUILD.bazel
- grpc/testing/benchmark_service.proto
- grpc/testing/control.proto
- grpc/testing/empty.proto
- grpc/testing/messages.proto
- grpc/testing/payloads.proto
- grpc/testing/report_qps_scenario_service.proto
- grpc/testing/stats.proto
- grpc/testing/test.proto
- grpc/testing/worker_service.proto
This PR adds common java proto options to the testing files.
Particularly the 3 main options include
* Java multiple files = true
* Java package which is being set to io.grpc.testing
* Java outer classname which is being set to fileNameProto
> Add common java options to the testing/*.protos. 

- grpc/reflection/v1alpha/reflection.proto
Adding option to reflection v1alpha to allow go files to be generated from this repository.
With this change, we can remove the duplicate copy of reflection (v1alpha) from the grpc/grpc-go repository.
Referenced in https://github.com/grpc/grpc-go/issues/5684.
> Add go_package to reflection v1alpha

- BUILD.bazel
- grpc/service_config/service_config.proto
Also a couple of other cleanups:
- Add the missing `_experimental` suffix to the outlier detection config.
- Reorganize the fields a bit to be under the right comment headings.
- Add comments on the ring_hash min/max ring size fields matching the behavior described in https://github.com/grpc/proposal/pull/338.
> add RLS LB policy config

- .github/workflows/testing.yml
GitHub Actions has really, really bad default permissions, including write. This can be changed in the repository settings, but that doesn't protect forks and is harder to verify. Set the permissions actually needed by the testing workflow to avoid Actions accidentally having more power than they should.
> Set permissions for GitHub Actions

- grpc/testing/messages.proto
1. Add mention of the "*" matching.
2. Return entry type (Initial/Trailing)
3. Reshuffled some comments.
> Improvements for metadata matching

- BUILD.bazel
- grpc/lookup/v1/rls.proto
Add  application-specific optional `extensions` fields to `RouteLookupRequest` and `RouteLookupResponse` proto messages.
> Add application-specific optional `extensions` fields to rls.proto

- grpc/testing/messages.proto
1. Default value should not be a value that is in use.
2. Make enum nested so enum values are not global.
> Address protobuf linter warnings.

- grpc/health/v1/health.proto
This commit somewhat improves the documentation of `grpc.health.v1.Health`:
- It directs readers to [the specification](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), which feels a bit too long to inline into comments.
- It explains the semantics of the `Check` RPC a bit more thoroughly, clarifying that implementations should be idempotent and side effect free.
Hopefully, this PR faithfully follows the discussion with @ejona86 in #127.
> Improve documentation comments for health service

- grpc/testing/messages.proto
- grpc/testing/test.proto
I propose to add a ReturnAll method to a Hook server. This replaces the HookRequest with the Return method. Ultimately, this would allow us to completely remove the SendHookRequest method from the XdsUpdateHealthService when the tests no longer rely on it.
> [xds test] Add ReturnAll method to a HookServer

- grpc/gcp/handshaker.proto
Already internally-reviewed (see cl/589894002 and cl/589974172).
> Add network_latency_ms field to ALTS's NextHandshakeMessageReq.

- .bazelrc
- WORKSPACE
-std=c++14 is required by absl to increase the c++ version on multiple supported platforms.
CC @matthewstevenson88
Protobuf 25 drops support for Bazel 5. But 24 is still a relatively recent version and it gets us past the absl addition.
> Upgrade protobuf to 24.4

- .github/workflows/testing.yml
- BUILD.bazel
- MODULE.bazel
- MODULE.bazel.lock
- bazel/http_archives_extension.bzl
- bazel/switched_rules_extension.bzl
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> chore(bazel): add MODULE.bazel files for bzlmod

- grpc/gcp/s2a/common.proto
- grpc/gcp/s2a/s2a.proto
- grpc/gcp/s2a/s2a_context.proto
Context:
- https://github.com/grpc/grpc-java/pull/11113
- https://github.com/google/s2a-go/blob/main/README.md
> gRPC Java S2A protos

- MODULE.bazel
The module name was wrongly named first, it shall be aligned with the project name as it is done for other grpc bazel modules
> Correct module name

- BUILD.bazel
- grpc/gcp/s2a/s2a_context.proto
Update the bazel build to add targets for the s2a proto files. Fix syntax error in s2a_context.proto.
Fixes #155.
> Add bazel targets for s2a proto files

- grpc/channelz/v1/channelz.proto
- grpc/gcp/handshaker.proto
- grpc/reflection/v1alpha/reflection.proto
Fix three typos, related to https://github.com/protocolbuffers/protobuf/pull/17682 and https://github.com/grpc/grpc-go/pull/7487.
> Fix minor typos

- grpc/lookup/v1/rls_config.proto
Adding an optional field in HttpKeyBuilder to allow extraction of the HTTP verb/method in RLS route key.
> Support HTTP method extraction in RLS config

- grpc/service_config/service_config.proto
> service_config: add request_hash_header to ring hash config

- grpc/health/v1/health.proto
Clients cannot get a list of the services a certain server is watching to and their respective status.
In the context of Kubernetes, we have `livez` and `readyz` endpoints, by listing all the services a server is checking, we could return a response like the `/readyz?verbose` Kubernetes API returns:
```
[+]ping ok
[+]log ok
[+]etcd ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok …
```
> Add List method to gRPC Health service
